require_relative './entities/validation'
require_relative './entities/console'
require_relative './entities/taxes'
require_relative './entities/card'
require_relative './entities/account'
require_relative './entities/manager'
